<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>A. JURIN</title>
	<link rel="stylesheet" type="text/css" href="/assets/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/css/styles.css">
	<link rel="stylesheet" type="text/css" href="/assets/font-awesome/css/font-awesome.min.css">
</head>
<body data-target=".navbar-fixed-top">
	<main>
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Menu</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/homepage">
						<div>Axelle JURIN</div>
						<div id="postTitle">Conceptrice - Développeuse informatique</div>
					</a>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="/homepage">Accueil</a></li>
						<li><a href="/about">A propos</a></li>
						<li><a href="/skills">Compétences</a></li>
						<li><a href="/works">Réalisations</a></li>
						<li><a href="/contact">Contact</a></li>
					</ul>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>
		
		<!------ CONTENT --------->
			<?= isset($this->view) ? $this->view->getContent() : ''?>
		<!------ END ---------->
		
		<footer>
			<div>
				<a href="https://twitter.com/axellejurin" target="_blank">
					<span><i class="fa fa-twitter fa-2x"></i></span>
				</a>
				<a href="https://fr.linkedin.com/in/ajurin" target="_blank">
					<span><i class="fa fa-linkedin fa-2x"></i></span>
				</a>
				<a href="https://github.com/ajurin" target="_blank">
					<span><i class="fa fa-github fa-2x"></i></span>
				</a>
			</div>
		</footer>
	</main>

	<script type="text/javascript" src="/js/jquery-1.11.3.min.js"></script>
	<script type="text/javascript" src="/assets/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>