<!DOCTYPE html>
						<html style="height:100%; margin:0px; padding:0px;">
							<head>
								<meta http-equiv=Content-Type content="text/html; charset=UTF-8">
        						<meta content="MSHTML 6.00.6000.17092" name=GENERATOR>
							</head>
							<body style="height:100%; margin:0px; padding:0px; backgound-color=#EEEEEE;">
								<div style="width:100%; padding:10px; background-color:#20638C; color:#FFF; border-radius:5px;text-align:center;">
									<h1>Contact Axelle JURIN</h1>
									<h3>Conceptrice - Développeuse informatique</h3>
								</div>
								<div style="margin:10%;">
									De la part de '.$name.'<br/>
									<p>'. $message .'<p>
								</div>
								<div style="height:100%; padding:10px; text-align:center; position:relative; bottom:0px; border-radius:5px; background-color:#20638C; color:#FFF;">
									<a href="https://twitter.com/axellejurin" target="_blank" style="padding:5px;">Twitter</a>
									<a href="https://fr.linkedin.com/in/ajurin" target="_blank" style="padding:5px;">Linkdin</a>
									<a href="https://github.com/ajurin" target="_blank" style="padding:5px;">GitHub</a>
									<a href="" target="_blank" style="padding:5px;">Viadeo</a>
								</div>
							</body>
						</html>'