<section id="about">
	<div>
		<div>
			<h2>A propos</h2>
			<p class="text-justify">
				Ma passion pour l'informatique est née il y a plus de 7ans.
				Durant ces années, j'ai aquis de bonnes bases en algorithme ce qui m'a permis 
				d'apprendre de multiples languages orientés web et programmation (procédurale et objet).
				Organisée et minutieuse dans mon travail je peux être patiente et diplomate face au client.
				Aujourd'hui je souhaite approfondir et valider mes connaissances par le bias d'une alternance.  
				
			</p>
		</div>
		<div class="row row-centered">
			<div class="col-xs-12 col-sm-6 col-centered">
				<!-- icon training -->
				<span class="fa-stack fa-3x icon">
					<i class="fa fa-square fa-stack-2x"></i>
					<i class="fa fa-graduation-cap fa-stack-1x"></i>
				</span>
				<div  id="training">
					<h3>Formations</h3>
					<ul>

						<?php if( isset($this->listTraining) && !empty($this->listTraining) ){ ?>
							<?php foreach ( $this->listTraining as $value ) {?>
								<li>
									<div class="date_lieu">
										<span>
											<?= $value->getDate() ?>
										</span>
										<em>
											<?= $value->getSchool(). ' ' . $value->getTown() ?>
										</em>
									</div>
									<div class="title">
										<?= $value->getTitle() ?>
									</div>
								</li>
							<?php }?>
						<?php }?>

						<li>
							<div class="date_lieu">
								<span>06/2015 - 11/2015</span>
								<em>IP formation Villeurbanne</em>
							</div>
							<div class="title">CARED : DEVELOPPER WEB</div>
						</li>

						<li>
							<div class="date_lieu">
								<span>09/2014 - 12/2014</span>
								<em>Greta Lyon 8</em>
							</div>
							<div class="title">DEVELOPEUR JAVA / J2EE</div>
						</li>

						<li>
							<div class="date_lieu">
								<span>09/2010 - 06/2012</span>
								<em>Lycée Saint Romain en Gal</em>
							</div>
							<div class="title">BTS INFORMATIQUE DE GESTION
								<div>option Développeur d'application</div>
							</div>
						</li>

						<li>
							<div class="date_lieu">
								<span>09/2007 - 06/2008</span>
								<em>Université Lyon 2</em>
							</div>
							<div class="title">CERTIFICAT INFORMATIQUE ET INTERNET <div>niveau 1</div></div>
						</li>

						<li>
							<div class="date_lieu">
								<span>09/2007 - 06/2008</span>
								<em>Université Lyon 2</em>
							</div>
							<div class="title">INFORMATION ET COMMUNICATION</div>
						</li>

						<li>
							<div class="date_lieu">
								<span>09/2005 - 06/2007</span>
								<em>Lycée Robet Doisneau</em>
							</div>
							<div class="title">BAC SCIENTIFIQUE<div>option Science Vie de la Terre</div></div>
						</li>

					</ul>
				</div>
			</div>

			<div class="col-xs-12 col-sm-6 col-centered">
				<!-- icon jobs -->
				<span class="fa-stack fa-3x icon">
					<i class="fa fa-square fa-stack-2x"></i>
					<i class="fa fa-code fa-stack-1x"></i>
				</span>
				<div id="jobs">
					<h3>Experiences</h3>
					<ul>
						<?php if( isset($this->listJobs) && !empty($this->listJobs)) {?>
							<?php foreach ( $this->listJobs as $job ) {?>
							<li>
								<div class="date_lieu">
									<span>
										<?=  $job->getDate() ?>
									</span>
									<em>
										<?= $job->getCompany(). ' ' . $job->getTown() ?>
									</em>
								</div>
								<div class="title">
									<?= $job->getTitle() ?>
								</div>
								<ul class="description">
									<?php foreach ($job->getDescription() as $descrip){?>
									<?= '<li>'.$descrip.'</li>' ?>
									<?php }?>
								</ul>
							</li>
							<?php }?>
						<?php }?>				
						<li>
							<div class="date_lieu">
								<span>09/2015</span>
								<em>The Legendary Wines - Lyon</em>
							</div>
							<div class="title">STAGE - DEVELOPPEUSE WEB</div>
							<ul class="description">
								<li>Organisation d'une base de données</li>
								<li>Gestion d'un compte MailChimp</li>
								<li>Mise en place d'une campagne d'emailing</li>
							</ul>
						</li>
						<li>
							<div class="date_lieu">
								<span>01/2012 - 02/2012</span>
								<em>Association Bridge club - Vienne</em>
							</div>
							<div class="title">STAGE - DEVELOPPEUSE WEB</div>
							<ul class="description">
								<li>Mise en place d'un cahier des charges</li>
								<li>Création d'une base de données MySQL</li>
								<li>Développement d'un site en HTML/CSS/PHP</li>
							</ul>
						</li>
						<li>
							<div class="date_lieu">
								<span>05/2011 - 06/2011</span>
								<em>SERVIZEN - Lyon 3</em>
							</div>
							<div class="title">STAGE - DEVELOPPEUSE WEB</div>
							<ul class="description">
								<li>Intégration d'un site avec HTML/CSS/JavaScript</li>
								<li>Gestion formulaire de contact avec PHP</li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-sm-6 col-centered">
				<a class="btn btn-default" id="btnCV" href="/files/CV_Axelle_JURIN.pdf" target="_blank">Télécharger mon CV</a>
			</div>
		</div>
	</div>
</section>