<?php
require_once ROOT_PATH."/".PUBLIC_FOLDER."/php/send.php"; 


?>

<section id="contact">
	<div class="row">
		
		<div id="formContact" class="col-xs-12 col-sm-7">
			<div>
				<h2>Contact</h2>
				<div>
					<?php 
						if(isset($errors) && !empty($errors))
						{
							echo '<ul id="errors">';
							foreach ($errors as $error)
							{
								echo '<li>' . $error . '</li>';
							}
							echo '<ul>';
						} elseif (isset($mail) && $mail) {
							echo '<div id="send">Votre message a bien été envoyé.</div>';
						}
					?>
				</div>
				<form action="" method="post">
					<div class="form-group">
						<label for="name">Nom et Prénom :</label>
						<input type="text" class="form-control" id="name" name="name" placeholder="Nom Prénom" value="<?php if (isset($name)&& !empty($name)) echo $name;?>">
					</div>
					<div class="form-group">
						<label for="subject">Sujet :</label>
						<input type="text" class="form-control" id="subject" name="subject" placeholder="Sujet"  value="<?php if (isset($subject) && !empty($subject)) echo $subject; ?>">
					</div>
					<div class="form-group">
						<label for="email">Email :</label>
						<input type="email" class="form-control" id="email" name="email" placeholder="Email"  value="<?php if (isset($email) && !empty($email)) echo $email;?>">
					</div>
					<div class="form-group">
						<label for="message">Message :</label>
						<textarea class="form-control" id="message" name="message" placeholder="Votre message..." rows="5"><?php if (isset($message) && !empty($message)) echo $message; else echo '';?></textarea>
					</div>
					<!-- 
					<div class="checkbox">
						<label>
							<input type="checkbox" name="copy"> Recevez une copy 
						</label>
					</div>
					 -->
					<button type="submit" class="btn btn-primary" name="send">Envoyer</button>
				</form>
			</div>
		</div>
		<div id="info" class="col-xs-12 col-sm-5">
			<div>
				<ul>
					<li><i class="fa fa-female fa-x3"></i>26 ans</li>
					<li><i class="fa fa-map-marker fa-x3"></i>BRON</li>
					<li><i class="fa fa-car fa-x3"></i>Permis B</li>
					<li><a href=""><i class="fa fa-envelope fa-x3"></i><img alt="" src="/images/email.png"></a></li>
					<li>
						<script type="text/javascript">
							mailto('mailto','jurin','axelle','gmail','com');
						</script>
					</li>
					<li><i class="fa fa-mobile fa-x3"></i><img alt="" src="/images/tel.png"></li>
				</ul>
			</div>
		</div>
	</div>

</section>
<script type="text/javascript">
	function mailto(a, b, c, d, e){
		document.write('<a href:"'+a+':'+b+c+'@'+d+'.'+e+'">');
		document.write('<i class="fa fa-envelope fa-x3"></i><img alt="" src="/images/email.png"></a>');
		echo 'bien';
	}
</script>