<section id="works">
	<div>
		<h2>Réalisations</h2>
		<div class="row row-centered">
			<?php if ( isset($this->listWorks) && !empty($list->listWork) ) {?>
				<?php foreach ($this->listWorks as $key => $work) {?>
					<!-- PROJECT <?= $key ?> -->
					<img class="col-xs-12 col-sm-6 col-centered" src="<?= $work->getUrlImg()?>" alt="project<?= $key ?>" data-toggle="modal" data-target="#project<?= $key ?>">
					<!-- Modal project1 -->
					<div class="modal fade" id="project<?= $key ?>" tabindex="-1" role="dialog" aria-labelledby="modalProject<?= $key ?>">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
									<h3 id="modalProject<?= $key ?>" class="text-center"><?= $work->getTitle() ?></h3>
								</div>
								<div class="modal-body row">
									<div class="col-xs-12 col-sm-6">
										<img class="img-responsive" src="<?= $work->getUrlImg()?>" alt="project<?= $key ?>" />
									</div>
									<div class="col-xs-12 col-sm-6 description">
										<h4>Description</h4>
										<ul>
										<?php foreach ($work->getDescription() as $description) {?>
											<li>$description</li>
										<?php }?>
										</ul>
									</div>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
								</div>
							</div>
						</div>
					</div>
				<?php }?>
			<?php }?>
			
			
			<!-- PROJECT 1 -->
			<img class="col-xs-12 col-sm-6 col-centered" src="/images/p3.PNG" alt="project1" data-toggle="modal" data-target="#project1">
			<!-- Modal project1 -->
			<div class="modal fade" id="project1" tabindex="-1" role="dialog" aria-labelledby="modalProject1">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
							<h3 id="modalProject1" class="text-center">Réalisation du premier site SERVIZEN</h3>
						</div>
						<div class="modal-body row">
							<div class="col-xs-12 col-sm-6">
								<img class="img-responsive" src="/images/p3.PNG" alt="project1" />
							</div>
							<div class="col-xs-12 col-sm-6 description">
								<h4>Description</h4>
								<ul>
									<li>Intégration</li>
									<li>Utilisation de  HTML/CSS/JavaScript</li>
									<li>Gestion d'un formulaire de contact</li>
								</ul>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
						</div>
					</div>
				</div>
			</div>

			<!-- PROJECT 2 -->
			<img class="col-xs-12 col-sm-6 col-centered" src="/images/p1.PNG" alt="project2" data-toggle="modal" data-target="#project2">
			<!-- Modal project2 -->
			<div class="modal fade" id="project2" tabindex="-1" role="dialog" aria-labelledby="modalProject2">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h3 class="modal-title" id="modalProject2">Réalisation d'un template</h3>
						</div>
						<div class="modal-body row">
							<div class="col-xs-12 col-sm-6">
								<img class="img-responsive" src="/images/p1.PNG" alt="project2" />
							</div>
							<div class="col-xs-12 col-sm-6 description">
								<h4>Description</h4>
								<ul>
									<li>Intégration</li>
									<li>Utilisation de HTML/CSS</li>
								</ul>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
						</div>
					</div>
				</div>
			</div>
			
			<!-- PROJECT 3 -->
			<img class="col-xs-12 col-sm-6 col-centered" src="/images/p5.PNG" alt="project3" data-toggle="modal" data-target="#project3">
			<!-- Modal project3 -->
			<div class="modal fade" id="project3" tabindex="-1" role="dialog" aria-labelledby="modalProject3">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h3 class="modal-title" id="modalProject3">Puissace 4</h3>
						</div>
						<div class="modal-body row">
							<div class="col-xs-12 col-sm-6">
								<img class="img-responsive" src="/images/p5.PNG" alt="project3" />
							</div>
							<div class="col-xs-12 col-sm-6 description">
								<h4>Description</h4>
								<ul>
									<li>Programmation orienté object</li>
									<li>Langage : C#</li>
									<li>Architecture MVC (Modèle Vue Contrôleur)</li>
								</ul>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
						</div>
					</div>
				</div>
			</div>
			
			<!-- PROJECT 4 -->
			<img class="col-xs-12 col-sm-6 col-centered" src="/images/p4.PNG" alt="project4" data-toggle="modal" data-target="#project4">
			<!-- Modal project4 -->
			<div class="modal fade" id="project4" tabindex="-1" role="dialog" aria-labelledby="modalProject4">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h3 class="modal-title" id="modalProject4">Outils de gestion de cocktail</h3>
						</div>
						<div class="modal-body row">
							<div class="col-xs-12 col-sm-6">
								<img class="img-responsive" src="/images/p4.PNG" alt="project4" />
							</div>
							<div class="col-xs-12 col-sm-6 description">
								<h4>Description</h4>
								<ul>
									<li>Programmation orienté object</li>
									<li>Langage : C#</li>
									<li>Base de donnée MySQL</li>
								</ul>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
						</div>
					</div>
				</div>
			</div>
			
			<!-- PROJECT 5 -->
			<img class="col-xs-12 col-sm-6 col-centered" src="/images/p2.PNG" alt="project5" data-toggle="modal" data-target="#project5">
			<!-- Modal project4 -->
			<div class="modal fade" id="project5" tabindex="-1" role="dialog" aria-labelledby="modalProject5">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h3 class="modal-title" id="modalProject5">Portfolio</h3>
						</div>
						<div class="modal-body row">
							<div class="col-xs-12 col-sm-6">
								<img class="img-responsive" src="/images/p2.PNG" alt="project5" />
							</div>
							<div class="col-xs-12 col-sm-6 description">
								<h4>Description</h4>
								<ul>
									<li>Programation orienté object</li>
									<li>Architecture MVC</li>
									<li>Base de donnée MySQL</li>
									<li>Languages : HTML/CSS/PHP</li>
								</ul>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
						</div>
					</div>
				</div>
			</div>
			
		</div>
	</div>
</section>